//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsCreator.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InternalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormsCreator.Application.Resources.InternalMessages", typeof(InternalMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} couldn&apos;t be saved due to null data..
        /// </summary>
        public static string AddCannotInsertNullEx {
            get {
                return ResourceManager.GetString("AddCannotInsertNullEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An internal error occurred while trying to save the {0}..
        /// </summary>
        public static string AddInternalErrorEx {
            get {
                return ResourceManager.GetString("AddInternalErrorEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} couldn&apos;t be saved due to a property that exceeded the max length. Properties: {1}..
        /// </summary>
        public static string AddMaxLengthEx {
            get {
                return ResourceManager.GetString("AddMaxLengthEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} couldn&apos;t be saved due to an internal problem. Properties: {1}..
        /// </summary>
        public static string AddRefConstraintEx {
            get {
                return ResourceManager.GetString("AddRefConstraintEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The answers couldn&apos;t be updated..
        /// </summary>
        public static string AllAnswersNotUpdated {
            get {
                return ResourceManager.GetString("AllAnswersNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The questions couldn&apos;t be updated..
        /// </summary>
        public static string AllQuestionsNotUpdated {
            get {
                return ResourceManager.GetString("AllQuestionsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An internal error occurred while counting data of {0}..
        /// </summary>
        public static string CountingError {
            get {
                return ResourceManager.GetString("CountingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An internal error occurred while trying to delete the {0}..
        /// </summary>
        public static string DeleteException {
            get {
                return ResourceManager.GetString("DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An internal error occurred while fetching get data of {0}..
        /// </summary>
        public static string FetchDataException {
            get {
                return ResourceManager.GetString("FetchDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect password..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some answer couldn&apos;t be updated..
        /// </summary>
        public static string SomeAnswerNotUpdated {
            get {
                return ResourceManager.GetString("SomeAnswerNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some questions couldn&apos;t be updated..
        /// </summary>
        public static string SomeQuestionsNotUpdated {
            get {
                return ResourceManager.GetString("SomeQuestionsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The permission couldn&apos;t be revoked..
        /// </summary>
        public static string TemplateAcessPermissionNotRevoked {
            get {
                return ResourceManager.GetString("TemplateAcessPermissionNotRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The template couldn&apos;t be deleted..
        /// </summary>
        public static string TemplateNotDeleted {
            get {
                return ResourceManager.GetString("TemplateNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The template doesn&apos;t exist..
        /// </summary>
        public static string TemplateNotFoundMessage {
            get {
                return ResourceManager.GetString("TemplateNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The template couldn&apos;t be updated..
        /// </summary>
        public static string TemplateNotUpdated {
            get {
                return ResourceManager.GetString("TemplateNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} couldn&apos;t be updated due to null data..
        /// </summary>
        public static string UpdCannotInsertNullEx {
            get {
                return ResourceManager.GetString("UpdCannotInsertNullEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An internal error occurred while trying to update the {0}..
        /// </summary>
        public static string UpdInternalErrorEx {
            get {
                return ResourceManager.GetString("UpdInternalErrorEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} couldn&apos;t be updated due to a property that exceeded the max length. Properties {1}..
        /// </summary>
        public static string UpdMaxLengthEx {
            get {
                return ResourceManager.GetString("UpdMaxLengthEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} couldn&apos;t be updated due to an internal problem. Properties: {1}..
        /// </summary>
        public static string UpdRefConstraintEx {
            get {
                return ResourceManager.GetString("UpdRefConstraintEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user couldn&apos;t be deleted..
        /// </summary>
        public static string UserNotDeleted {
            get {
                return ResourceManager.GetString("UserNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user couldn&apos;t be found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user couldn&apos;t be updated..
        /// </summary>
        public static string UserNotUpdated {
            get {
                return ResourceManager.GetString("UserNotUpdated", resourceCulture);
            }
        }
    }
}
