//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsCreator.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormsCreator.Application.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the column field..
        /// </summary>
        public static string AnswerColumnMax {
            get {
                return ResourceManager.GetString("AnswerColumnMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The column cannot be empty if you are not using the simple types of question..
        /// </summary>
        public static string AnswerColumnNotEmpty {
            get {
                return ResourceManager.GetString("AnswerColumnNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The answer cannot contain the form id itself..
        /// </summary>
        public static string AnswerFormId {
            get {
                return ResourceManager.GetString("AnswerFormId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The question id cannot be empty..
        /// </summary>
        public static string AnswerQuestionId {
            get {
                return ResourceManager.GetString("AnswerQuestionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the row field..
        /// </summary>
        public static string AnswerRowMax {
            get {
                return ResourceManager.GetString("AnswerRowMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The row cannot be empty if you are not using the simple types of question..
        /// </summary>
        public static string AnswerRowNotEmpty {
            get {
                return ResourceManager.GetString("AnswerRowNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the value field..
        /// </summary>
        public static string AnswerValueMax {
            get {
                return ResourceManager.GetString("AnswerValueMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value cannot be empty if you are not using a multiselector type of question..
        /// </summary>
        public static string AnswerValueNotEmpty {
            get {
                return ResourceManager.GetString("AnswerValueNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the comment..
        /// </summary>
        public static string CommentContentMax {
            get {
                return ResourceManager.GetString("CommentContentMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The comment cannot be empty..
        /// </summary>
        public static string CommentContentNotEmpty {
            get {
                return ResourceManager.GetString("CommentContentNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The template id cannot be empty..
        /// </summary>
        public static string CommonTemplateId {
            get {
                return ResourceManager.GetString("CommonTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The form must have answers..
        /// </summary>
        public static string FormAnswersNotEmpty {
            get {
                return ResourceManager.GetString("FormAnswersNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The form id cannot be empty..
        /// </summary>
        public static string FormId {
            get {
                return ResourceManager.GetString("FormId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are not forms at this moment..
        /// </summary>
        public static string NoFormsText {
            get {
                return ResourceManager.GetString("NoFormsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the description..
        /// </summary>
        public static string QuestionDescMax {
            get {
                return ResourceManager.GetString("QuestionDescMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The column cannot be empty when the row and value are empty..
        /// </summary>
        public static string QuestionOptionColumnNotEmpty {
            get {
                return ResourceManager.GetString("QuestionOptionColumnNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The row cannot be empty when the column and the value are empty..
        /// </summary>
        public static string QuestionOptionRowNotEmpty {
            get {
                return ResourceManager.GetString("QuestionOptionRowNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the value..
        /// </summary>
        public static string QuestionOptionValueMax {
            get {
                return ResourceManager.GetString("QuestionOptionValueMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value cannot be empty..
        /// </summary>
        public static string QuestionOptionValueNotEmpty {
            get {
                return ResourceManager.GetString("QuestionOptionValueNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the question..
        /// </summary>
        public static string QuestionTextMax {
            get {
                return ResourceManager.GetString("QuestionTextMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The question title cannot be empty..
        /// </summary>
        public static string QuestionTextNotEmpty {
            get {
                return ResourceManager.GetString("QuestionTextNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The question type is not valid..
        /// </summary>
        public static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the tag..
        /// </summary>
        public static string TagNameMax {
            get {
                return ResourceManager.GetString("TagNameMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The tag name cannot be empty..
        /// </summary>
        public static string TagNameNotEmpty {
            get {
                return ResourceManager.GetString("TagNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The list of user ids cannot be empty..
        /// </summary>
        public static string TemplateAccessRangeUserIdsNotEmpty {
            get {
                return ResourceManager.GetString("TemplateAccessRangeUserIdsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the description..
        /// </summary>
        public static string TemplateDescMax {
            get {
                return ResourceManager.GetString("TemplateDescMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The template description cannot be empty..
        /// </summary>
        public static string TemplateDescNotEmpty {
            get {
                return ResourceManager.GetString("TemplateDescNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The uploaded file must be an image..
        /// </summary>
        public static string TemplateImageIsNotImage {
            get {
                return ResourceManager.GetString("TemplateImageIsNotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is public?.
        /// </summary>
        public static string TemplateIsPublic {
            get {
                return ResourceManager.GetString("TemplateIsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The template must contain questions..
        /// </summary>
        public static string TemplateQuestionsNotEmpty {
            get {
                return ResourceManager.GetString("TemplateQuestionsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have exceeded the max length of the title..
        /// </summary>
        public static string TemplateTitleMax {
            get {
                return ResourceManager.GetString("TemplateTitleMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The template title cannot be empty..
        /// </summary>
        public static string TemplateTitleNotEmpty {
            get {
                return ResourceManager.GetString("TemplateTitleNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The template must include a topic..
        /// </summary>
        public static string TemplateTopicId {
            get {
                return ResourceManager.GetString("TemplateTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This user was registered by an external service, please use the external service to log in..
        /// </summary>
        public static string UserExternalService {
            get {
                return ResourceManager.GetString("UserExternalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username/email field cannot be empty..
        /// </summary>
        public static string UserLoginUserOrEmail {
            get {
                return ResourceManager.GetString("UserLoginUserOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must be entered..
        /// </summary>
        public static string UserLoginWithoutPassword {
            get {
                return ResourceManager.GetString("UserLoginWithoutPassword", resourceCulture);
            }
        }
    }
}
