//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsCreator.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormsCreator.Application.Resources.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account created.
        /// </summary>
        public static string AccountCreatedText {
            get {
                return ResourceManager.GetString("AccountCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new tag.
        /// </summary>
        public static string AddNewTag {
            get {
                return ResourceManager.GetString("AddNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add a new tag to use it.
        /// </summary>
        public static string AddNewTagToUse {
            get {
                return ResourceManager.GetString("AddNewTagToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add or remove user permission to the template.
        /// </summary>
        public static string AddOrRemovePermissionToTemplate {
            get {
                return ResourceManager.GetString("AddOrRemovePermissionToTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add permission.
        /// </summary>
        public static string AddPermission {
            get {
                return ResourceManager.GetString("AddPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply filters.
        /// </summary>
        public static string ApplyFiltersText {
            get {
                return ResourceManager.GetString("ApplyFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have an account? Sign up here.
        /// </summary>
        public static string AuthLoginDontHaveAcc {
            get {
                return ResourceManager.GetString("AuthLoginDontHaveAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email or Username.
        /// </summary>
        public static string AuthLoginEmailUser {
            get {
                return ResourceManager.GetString("AuthLoginEmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue with Google.
        /// </summary>
        public static string AuthLoginGoogle {
            get {
                return ResourceManager.GetString("AuthLoginGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string AuthLoginPassword {
            get {
                return ResourceManager.GetString("AuthLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string AuthLoginSignIn {
            get {
                return ResourceManager.GetString("AuthLoginSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string AuthLoginTitle {
            get {
                return ResourceManager.GetString("AuthLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string AuthRegisterEmail {
            get {
                return ResourceManager.GetString("AuthRegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Do you already have an account? Sign In here.
        /// </summary>
        public static string AuthRegisterHaveAcc {
            get {
                return ResourceManager.GetString("AuthRegisterHaveAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string AuthRegisterUserName {
            get {
                return ResourceManager.GetString("AuthRegisterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string AuthSignUp {
            get {
                return ResourceManager.GetString("AuthSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes made.
        /// </summary>
        public static string ChangesMade {
            get {
                return ResourceManager.GetString("ChangesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The changes were made successfully..
        /// </summary>
        public static string ChangesSuccessfully {
            get {
                return ResourceManager.GetString("ChangesSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change theme.
        /// </summary>
        public static string ChangeThemeText {
            get {
                return ResourceManager.GetString("ChangeThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose anything.
        /// </summary>
        public static string ChooseAnything {
            get {
                return ResourceManager.GetString("ChooseAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create salesforce account.
        /// </summary>
        public static string CreateSalesforceAcc {
            get {
                return ResourceManager.GetString("CreateSalesforceAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Jira ticket.
        /// </summary>
        public static string CreateTicketJiraText {
            get {
                return ResourceManager.GetString("CreateTicketJiraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed changes.
        /// </summary>
        public static string FailedChanges {
            get {
                return ResourceManager.GetString("FailedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Answer the form.
        /// </summary>
        public static string FormAnswerTemplateTitle {
            get {
                return ResourceManager.GetString("FormAnswerTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit submitted form.
        /// </summary>
        public static string FormEditFormTitle {
            get {
                return ResourceManager.GetString("FormEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Answered.
        /// </summary>
        public static string FormsByTemplateAnswered {
            get {
                return ResourceManager.GetString("FormsByTemplateAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forms by template.
        /// </summary>
        public static string FormsByTemplateTitle {
            get {
                return ResourceManager.GetString("FormsByTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OR.
        /// </summary>
        public static string GenericOR {
            get {
                return ResourceManager.GetString("GenericOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get by tags.
        /// </summary>
        public static string GetByTags {
            get {
                return ResourceManager.GetString("GetByTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get by text search.
        /// </summary>
        public static string GetByTextSearch {
            get {
                return ResourceManager.GetString("GetByTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get by topics.
        /// </summary>
        public static string GetByTopics {
            get {
                return ResourceManager.GetString("GetByTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start now!.
        /// </summary>
        public static string HomeIndexButtonStart {
            get {
                return ResourceManager.GetString("HomeIndexButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You might be interested.
        /// </summary>
        public static string HomeIndexCouldInterest {
            get {
                return ResourceManager.GetString("HomeIndexCouldInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explore templates from various users and complete them..
        /// </summary>
        public static string HomeIndexMainSubtitle {
            get {
                return ResourceManager.GetString("HomeIndexMainSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create your own templates and share them..
        /// </summary>
        public static string HomeIndexMainTitle {
            get {
                return ResourceManager.GetString("HomeIndexMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Most popular templates.
        /// </summary>
        public static string HomeIndexMostPopular {
            get {
                return ResourceManager.GetString("HomeIndexMostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no templates for now..
        /// </summary>
        public static string HomeIndexNoTemplates {
            get {
                return ResourceManager.GetString("HomeIndexNoTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creator.
        /// </summary>
        public static string HomeIndexTableCreator {
            get {
                return ResourceManager.GetString("HomeIndexTableCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forms.
        /// </summary>
        public static string HomeIndexTableForms {
            get {
                return ResourceManager.GetString("HomeIndexTableForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Likes.
        /// </summary>
        public static string HomeIndexTableLikes {
            get {
                return ResourceManager.GetString("HomeIndexTableLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags.
        /// </summary>
        public static string HomeIndexTableTags {
            get {
                return ResourceManager.GetString("HomeIndexTableTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string HomeIndexTableTitle {
            get {
                return ResourceManager.GetString("HomeIndexTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Topic.
        /// </summary>
        public static string HomeIndexTableTopic {
            get {
                return ResourceManager.GetString("HomeIndexTableTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is blocked?.
        /// </summary>
        public static string IsBlockedText {
            get {
                return ResourceManager.GetString("IsBlockedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is public?.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Template.
        /// </summary>
        public static string MainNavbarCreateTemplate {
            get {
                return ResourceManager.GetString("MainNavbarCreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string MainNavBarHomeName {
            get {
                return ResourceManager.GetString("MainNavBarHomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change language.
        /// </summary>
        public static string MainNavbarLang {
            get {
                return ResourceManager.GetString("MainNavbarLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string MainNavbarLogin {
            get {
                return ResourceManager.GetString("MainNavbarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage users.
        /// </summary>
        public static string MainNavbarManageUsers {
            get {
                return ResourceManager.GetString("MainNavbarManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My forms.
        /// </summary>
        public static string MainNavbarMyForms {
            get {
                return ResourceManager.GetString("MainNavbarMyForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Templates.
        /// </summary>
        public static string MainNavbarMyTemplates {
            get {
                return ResourceManager.GetString("MainNavbarMyTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type Something.
        /// </summary>
        public static string MainNavBarSearchText {
            get {
                return ResourceManager.GetString("MainNavBarSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Out.
        /// </summary>
        public static string MainNavbarSignOut {
            get {
                return ResourceManager.GetString("MainNavbarSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Templates list.
        /// </summary>
        public static string MainNavbarTemplatesList {
            get {
                return ResourceManager.GetString("MainNavbarTemplatesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Templates.
        /// </summary>
        public static string MainNavbarTemplatesText {
            get {
                return ResourceManager.GetString("MainNavbarTemplatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi {0}!.
        /// </summary>
        public static string MainNavbarUsernameSalute {
            get {
                return ResourceManager.GetString("MainNavbarUsernameSalute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage acess.
        /// </summary>
        public static string ManageAccess {
            get {
                return ResourceManager.GetString("ManageAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are not forms at this moment..
        /// </summary>
        public static string NoFormsText {
            get {
                return ResourceManager.GetString("NoFormsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Post comment.
        /// </summary>
        public static string PostComment {
            get {
                return ResourceManager.GetString("PostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove permission.
        /// </summary>
        public static string RemovePermission {
            get {
                return ResourceManager.GetString("RemovePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Review form.
        /// </summary>
        public static string ReviewFormText {
            get {
                return ResourceManager.GetString("ReviewFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The salesforce account was created successfully..
        /// </summary>
        public static string SalesforceAccCreated {
            get {
                return ResourceManager.GetString("SalesforceAccCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See form.
        /// </summary>
        public static string SeeFormText {
            get {
                return ResourceManager.GetString("SeeFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See profile.
        /// </summary>
        public static string SeeProfileText {
            get {
                return ResourceManager.GetString("SeeProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        public static string SimpleWordAction {
            get {
                return ResourceManager.GetString("SimpleWordAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string SimpleWordActive {
            get {
                return ResourceManager.GetString("SimpleWordActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Answer.
        /// </summary>
        public static string SimpleWordAnswer {
            get {
                return ResourceManager.GetString("SimpleWordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blocked.
        /// </summary>
        public static string SimpleWordBlocked {
            get {
                return ResourceManager.GetString("SimpleWordBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string SimpleWordClose {
            get {
                return ResourceManager.GetString("SimpleWordClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string SimpleWordCode {
            get {
                return ResourceManager.GetString("SimpleWordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Column.
        /// </summary>
        public static string SimpleWordColumn {
            get {
                return ResourceManager.GetString("SimpleWordColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment.
        /// </summary>
        public static string SimpleWordComment {
            get {
                return ResourceManager.GetString("SimpleWordComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string SimpleWordDelete {
            get {
                return ResourceManager.GetString("SimpleWordDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string SimpleWordDescription {
            get {
                return ResourceManager.GetString("SimpleWordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string SimpleWordEdit {
            get {
                return ResourceManager.GetString("SimpleWordEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High.
        /// </summary>
        public static string SimpleWordHigh {
            get {
                return ResourceManager.GetString("SimpleWordHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low.
        /// </summary>
        public static string SimpleWordLow {
            get {
                return ResourceManager.GetString("SimpleWordLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium.
        /// </summary>
        public static string SimpleWordMedium {
            get {
                return ResourceManager.GetString("SimpleWordMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        public static string SimpleWordMenu {
            get {
                return ResourceManager.GetString("SimpleWordMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string SimpleWordMessage {
            get {
                return ResourceManager.GetString("SimpleWordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string SimpleWordName {
            get {
                return ResourceManager.GetString("SimpleWordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string SimpleWordNo {
            get {
                return ResourceManager.GetString("SimpleWordNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option.
        /// </summary>
        public static string SimpleWordOption {
            get {
                return ResourceManager.GetString("SimpleWordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Priority.
        /// </summary>
        public static string SimpleWordPriority {
            get {
                return ResourceManager.GetString("SimpleWordPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role.
        /// </summary>
        public static string SimpleWordRole {
            get {
                return ResourceManager.GetString("SimpleWordRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Row.
        /// </summary>
        public static string SimpleWordRow {
            get {
                return ResourceManager.GetString("SimpleWordRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string SimpleWordStatus {
            get {
                return ResourceManager.GetString("SimpleWordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submit.
        /// </summary>
        public static string SimpleWordSubmit {
            get {
                return ResourceManager.GetString("SimpleWordSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summary.
        /// </summary>
        public static string SimpleWordSummary {
            get {
                return ResourceManager.GetString("SimpleWordSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Understood.
        /// </summary>
        public static string SimpleWordUnderstood {
            get {
                return ResourceManager.GetString("SimpleWordUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string SimpleWordUsers {
            get {
                return ResourceManager.GetString("SimpleWordUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string SimpleWordYes {
            get {
                return ResourceManager.GetString("SimpleWordYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add column.
        /// </summary>
        public static string TemplateAddColumn {
            get {
                return ResourceManager.GetString("TemplateAddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add option.
        /// </summary>
        public static string TemplateAddOption {
            get {
                return ResourceManager.GetString("TemplateAddOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add row.
        /// </summary>
        public static string TemplateAddRow {
            get {
                return ResourceManager.GetString("TemplateAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checkbox grid question.
        /// </summary>
        public static string TemplateCheckboxGridQuestion {
            get {
                return ResourceManager.GetString("TemplateCheckboxGridQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checkbox question.
        /// </summary>
        public static string TemplateCheckboxQuestion {
            get {
                return ResourceManager.GetString("TemplateCheckboxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add the users you want to answer this template.
        /// </summary>
        public static string TemplateCreateAddUsers {
            get {
                return ResourceManager.GetString("TemplateCreateAddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Checkbox Grid Question.
        /// </summary>
        public static string TemplateCreatorAddCheckboxGrid {
            get {
                return ResourceManager.GetString("TemplateCreatorAddCheckboxGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Checkbox Question.
        /// </summary>
        public static string TemplateCreatorAddCheckboxQuestion {
            get {
                return ResourceManager.GetString("TemplateCreatorAddCheckboxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Dropdown Question.
        /// </summary>
        public static string TemplateCreatorAddDropdownQuestion {
            get {
                return ResourceManager.GetString("TemplateCreatorAddDropdownQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Multiple Choice Question.
        /// </summary>
        public static string TemplateCreatorAddMultipleChoice {
            get {
                return ResourceManager.GetString("TemplateCreatorAddMultipleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Multiple Choice Grid Question.
        /// </summary>
        public static string TemplateCreatorAddMultipleChoiceGrid {
            get {
                return ResourceManager.GetString("TemplateCreatorAddMultipleChoiceGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Number Question.
        /// </summary>
        public static string TemplateCreatorAddNumberQuestion {
            get {
                return ResourceManager.GetString("TemplateCreatorAddNumberQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Text Question.
        /// </summary>
        public static string TemplateCreatorAddTextQuestion {
            get {
                return ResourceManager.GetString("TemplateCreatorAddTextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter title.
        /// </summary>
        public static string TemplateCreatorEnterTitle {
            get {
                return ResourceManager.GetString("TemplateCreatorEnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Template.
        /// </summary>
        public static string TemplateCreatorSave {
            get {
                return ResourceManager.GetString("TemplateCreatorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template editor.
        /// </summary>
        public static string TemplateCreatorTemplateEditor {
            get {
                return ResourceManager.GetString("TemplateCreatorTemplateEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create template.
        /// </summary>
        public static string TemplateCreatorTitle {
            get {
                return ResourceManager.GetString("TemplateCreatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tools.
        /// </summary>
        public static string TemplateCreatorTools {
            get {
                return ResourceManager.GetString("TemplateCreatorTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dropdown question.
        /// </summary>
        public static string TemplateDropdownQuestion {
            get {
                return ResourceManager.GetString("TemplateDropdownQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit template.
        /// </summary>
        public static string TemplateEditTemplate {
            get {
                return ResourceManager.GetString("TemplateEditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your question.
        /// </summary>
        public static string TemplateEnterQuestion {
            get {
                return ResourceManager.GetString("TemplateEnterQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is public?.
        /// </summary>
        public static string TemplateIsPublic {
            get {
                return ResourceManager.GetString("TemplateIsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple choice grid question.
        /// </summary>
        public static string TemplateMultipleChoiceGrid {
            get {
                return ResourceManager.GetString("TemplateMultipleChoiceGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple choice question.
        /// </summary>
        public static string TemplateMultipleChoiceQuestion {
            get {
                return ResourceManager.GetString("TemplateMultipleChoiceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number question.
        /// </summary>
        public static string TemplateNumberQuestion {
            get {
                return ResourceManager.GetString("TemplateNumberQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text question.
        /// </summary>
        public static string TemplateTextQuestion {
            get {
                return ResourceManager.GetString("TemplateTextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template Image (optional).
        /// </summary>
        public static string TemplateUploadImage {
            get {
                return ResourceManager.GetString("TemplateUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text search.
        /// </summary>
        public static string TextSearch {
            get {
                return ResourceManager.GetString("TextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to get all records? (If not checked, blocking filter will be used.).
        /// </summary>
        public static string UserIndexGetAllText {
            get {
                return ResourceManager.GetString("UserIndexGetAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to filter by blocked users? (Only used if the first filter is disabled).
        /// </summary>
        public static string UserIndexGetBlockedMessage {
            get {
                return ResourceManager.GetString("UserIndexGetBlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grant admin.
        /// </summary>
        public static string UserIndexGrantAdmin {
            get {
                return ResourceManager.GetString("UserIndexGrantAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration date.
        /// </summary>
        public static string UserIndexRegistrationDate {
            get {
                return ResourceManager.GetString("UserIndexRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove admin.
        /// </summary>
        public static string UserIndexRemoveAdmin {
            get {
                return ResourceManager.GetString("UserIndexRemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of registered users.
        /// </summary>
        public static string UserIndexTitle {
            get {
                return ResourceManager.GetString("UserIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! Something went wrong.
        /// </summary>
        public static string UserIndexWentWrong {
            get {
                return ResourceManager.GetString("UserIndexWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See forms.
        /// </summary>
        public static string ViewForms {
            get {
                return ResourceManager.GetString("ViewForms", resourceCulture);
            }
        }
    }
}
